---
# tasks file for vector-role
#- name: get vector distr
#  ansible.builtin.get_url:
#    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
#    dest: "./vector_{{ vector_version }}-1_amd64.deb"
#    mode: 755

- name: Install vector package
  become: true
  ansible.builtin.apt:
    deb: "{{ vector_url }}"
    state: present
#./vector_{{ vector_version }}-1_amd64.deb
#  notify: restart vector

